### ISSUE TITLE
Add support for reading open office calc spreadsheets

### ISSUE THREAD

**Issue by 0xtrzy** [multiprocessio/datastation#131]
Please add open office format

**Comment by eatonphil** [comment]
@0xtrzy if you wanted open office calc support in dsq then that's available now and you can download the latest dsq from its new repo: https://github.com/multiprocessio/dsq.

If you wanted it in datastation (the GUI) then it will be released shortly in the next release.

**Comment by eatonphil** [comment]
This is now available: https://datastation.multiprocess.io/docs/0.6.0-release-notes.html.
