### ISSUE TITLE
[DSQ] Passing multiple files as different "tables" and doing joins

### ISSUE THREAD

**Issue by TheKnarf** [multiprocessio/datastation#132]
For the DSQ tool:

Seems like this tool would be a lot more useful if I could pass multiple files, naming each of them as a "table" name, and then doing joins on the data. Would be especially useful if one could do this with different datatype, maybe I have a couple of Excel documents, a csv and some json data coming from different datasources and I'd like to run a query over all of them.

Current workflows involves writing data importers to get all of the data into a proper SQL database server, and then running queries against to generate a report.

**Comment by eatonphil** [comment]
Thanks for the suggestion! Yes this should be doable just by extending the existing filename lookup/read logic.

**Comment by eatonphil** [comment]
Hey @TheKnarf this is now available in dsq. dsq now has its own repo at https://github.com/multiprocessio/dsq. Feel free to follow the install instructions there again and give it a whirl.

Thanks again for your feedback!

**Comment by TheKnarf** [comment]
Cool! Love that it got its own repo. Just starred the new repo. Great job!
