### ISSUE TITLE
Add language support for Deno (Typescript / Javascript Runtime)

### ISSUE THREAD

**Issue by aheissenberger** [multiprocessio/datastation#180]
Support for [Deno](https://deno.land) makes it much easier to write Javascript / Typescript which needs libraries as they will be pulled in by Deno automatically without the need of `npm` to install them.

**Comment by eatonphil** [comment]
Actually, this will work already. In the View menu click Settings and override the Node path to the path of your Deno installation. Let me know if that doesn't work.

**Comment by eatonphil** [comment]
I tested it out and nope it doesn't work already. Will need to add a new language entry for it.

**Comment by eatonphil** [comment]
I've added Deno support and it will be part of the next release.
