### ISSUE TITLE
language SQL / no such function: REGEXP

### ISSUE THREAD

**Issue by aheissenberger** [multiprocessio/datastation#182]
There is no support for
```sql
SELECT * FROM DM_getPanel(0) WHERE  url REGEXP '\b3\b'
```

**Comment by eatonphil** [comment]
Thanks! I'll have to look into this. The SQL panels use SQLite under the hood. Maybe I'm not loading the right extension.

In the meantime you can use `LIKE` if you'd like or you can do your filtering in JavaScript/Python before using the SQL panel.
