### ISSUE TITLE
Allow insecure Elastic connections

### ISSUE THREAD

**Issue by fosron** [multiprocessio/datastation#190]
I'm port forwarding to an internal ES cluster, and it has SSL/TLS setup. Trying to connect from Datastation just times out. I think i could avoid this by adding an exception for the whole OS, but i would prefer to be proactive on the spot and have an option to allow insecure connections.

**Comment by eatonphil** [comment]
By insecure do you mean it doesn't have TLS or that you don't want to validate the TLS cert?

Because DataStation should definitely support Elastic without TLS (there are tests in place for this).

**Comment by fosron** [comment]
Sorry, wasn't specific enough, i don't want to validate TLS because it's self-signed.

**Comment by eatonphil** [comment]
Gotcha! One thing I'm adding in the next release is support for custom CA certs. In the settings you'd add your CA and then it will try that throughout the app.

Will that solve the problem or do you still need the ability to skip validation?
