### ISSUE TITLE
Empty cells/fields are filled with values from preceding rows

### ISSUE THREAD

**Issue by steirico** [multiprocessio/datastation#217]
I came across this issue using [dsq](https://github.com/multiprocessio/dsq) and was able to narrow is down to this project.

The issue arises with the attached file [fail.xlsx](https://github.com/multiprocessio/datastation/files/8462526/fail.xlsx) which has the following structure:

A | B | C | D
-- | -- | -- | --
a1 | b1 | c1 | d1
a2 | b2 | c2 |  
a3 | b3 |   |  
a4 |   |   |  

Dumping the file's structure using `dsq` is as follow:

```bash
> dsq --pretty fail.xlsx
+----+----+----+----+
| A  | B  | C  | D  |
+----+----+----+----+
| a1 | b1 | c1 | d1 |
| a2 | b2 | c2 | d1 |
| a3 | b3 | c2 | d1 |
| a4 | b3 | c2 | d1 |
+----+----+----+----+
```

**Comment by eatonphil** [comment]
The fix is now released in dsq 0.14.0 https://github.com/multiprocessio/dsq/releases/tag/0.14.0
