### ISSUE TITLE
Add images / list of data sources to README

### ISSUE THREAD

**Issue by bbkane** [multiprocessio/datastation#248]
Hello,

DataStation looks really neat. Could I convince you to add some images and a list of data sources to the README instead of forcing people to click through the website to get this information? GitHub READMEs are as much of an intro to DataStation for potential new users as the home page is, so it makes sense to show off your hard work in the README.

**Comment by eatonphil** [comment]
Good idea! I just updated it. How does it look now?

**Comment by bbkane** [comment]
Oh that looks so much better! Thank you!!
