### ISSUE TITLE
Add role input to Snowflake data source UI

### ISSUE THREAD

**Issue by yozlet** [multiprocessio/datastation#258]
I tried out DataStation today to query Snowflake. My query required me to first switch my user role from the default. So, I have to execute two separate queries:
```sql
USE ROLE engineering; -- first, switch role

SELECT ... ; -- second, the actual query I wanted to run
```

Unfortunately, I couldn't make the two queries work together:

1. If I put the two queries in separate panel, the connection state doesn't seem to be carried over. Is DataStation recreating the connection for each panel? 
2. If I put the two queries in the same panel, I get this error:
```
time="..." level=error msg="error: 000008 (0A000): 
Actual statement count 2 did not match the desired statement count 1."
func="gosnowflake.(*snowflakeConn).queryContextInternal" file="connection.go:333"
```

**Comment by eatonphil** [comment]
Hey thanks for the report! It should be possible to describe the role in the data source where you specify database. It's possible that's available already as a query parameter but I need to look into it. Either way I should add a new optional role field to the data source so you can easily set it there.

I'll get back to you in a bit on what works now and should have the separate role field out shortly too.

**Comment by eatonphil** [comment]
In the meantime you should be able to add `?role=engineering` to the Account ID field. So if your Account ID was `qqlavcs-aa92002` before you could set `qqlavcs-aa92002?role=engineering` and then you won't need the `USE ROLE` statement. You can just execute your SQL query.
