### ISSUE TITLE
Support temporary security credentials in IAM

### ISSUE THREAD

**Issue by moltar** [multiprocessio/datastation#261]
Need to add another value `Security Token` (or `Session Token`).

Docs: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html

![screenshot-20220601T113857-GY4Ry0Ef](https://user-images.githubusercontent.com/491247/171386070-ab9058bf-5505-42fe-a643-fc749a8bd072.png)

---

A good example of it is from Postman:

![screenshot-20220601T114043-tahvOYSp](https://user-images.githubusercontent.com/491247/171386287-72743849-636f-44de-a97a-e0ccd0d61a34.png)

**Comment by eatonphil** [comment]
Good idea, thank you!
