### ISSUE TITLE
Process imported CSV files on the fly for light type conversion

### ISSUE THREAD

**Issue by fritzgrabo** [multiprocessio/datastation#264]
Hi!

I hope this hasn't been brought up before.

A user of the `ob-dsq` Emacs integration noticed in https://github.com/fritzgrabo/ob-dsq/issues/1 that all cell values of an imported CSV file are unconditionally parsed into strings.

Here's an example:

```shell
$ cat scores.csv
Name,Score
Fritz,90
Rainer,95
Fountainer,100

$ dsq --schema --pretty scores.csv
Array of
  Object of
    Name of
      string
    Score of
      string
```

I see how CSV doesn't carry type information for individual values, so treating everything as strings is probably the safest option. Also, it's what Go's [CSV reader](https://pkg.go.dev/encoding/csv#Reader.Read) does by default.

At the same time, it leads to unexpected results in queries:

```shell
$ dsq --pretty scores.csv "select * from {} where Score > 90"
+--------+-------+
|  Name  | Score |
+--------+-------+
| Rainer |    95 |
+--------+-------+
(1 row)
```

As a user, you'd have to know a bit about data types, operators and file formats to see what's going on here. You'd also have to know a bit about SQLite to come up with a way to work around the issue by type-casting values in the query:

```shell
$ dsq --pretty scores.csv "select * from {} where cast(Score as int) > 90"
+------------+-------+
|    Name    | Score |
+------------+-------+
| Rainer     |    95 |
| Fountainer |   100 |
+------------+-------+
(2 rows)
```

To help with this, I propose to do some light post-processing of the individual values of read CSV rows as they're imported in `transformCSV` (reads CSV rows as array of strings) and passed into `recordToMap` (luckily accepts arrays of _any_ type).

It'd probably suffice to let `strconv.Atoi` and `strconv.ParseFloat` try to convert the read value, and to keep it a string if they can't?

One downside of this is decreased performance, though. I came up with a naive implementation of my proposal and the effect is pretty visible in `Test_transformCSV_BENCHMARK` for a [CSV file with 24.6M rows / 18 columns](https://data.cityofnewyork.us/Transportation/2020-Yellow-Taxi-Trip-Data/kxp8-n2sj).

```shell
# unpatched
$ BENCHMARK=true go test -run Test_transformCSV_BENCHMARK
transform csv took 4m16.018390038s
PASS

# patched
$ dsq --schema --pretty scores.csv
Array of
  Object of
    Name of
      string
    Score of
      number

$ BENCHMARK=true go test -run Test_transformCSV_BENCHMARK
transform csv took 6m34.630924444s
PASS
```

The new caching feature probably helps with this: if a user has a CSV file of considerable size, I assume they'll use caching, so at least they'd have to take the performance hit only once.

In any case, before I start working on a proper PR for this, I wanted to ask your opinion:

- Is the issue an actual issue or should users just RTFM and learn to cast where needed?
- Is type conversion in CSV files too much magic?
- Is the decrease in performance worth the positive effect?; and related:
- Should this be a panel setting / `dsq` command line flag of some sorts?

Thanks!

**Comment by eatonphil** [comment]
Great points! Yes I'd be happy to take a PR if you make this conditional behavior as a panel setting. Google Sheets offers the same thing when importing CSV calling it type guessing or something.

You can expose it in dsq as a flag as well with `--convert-numbers` or something.

**Comment by fritzgrabo** [comment]
Thanks for the quick reply. I'll likely need help with the panel setting. I'll see how far I get, then throw a PR out with what I have to kick things off.

**Comment by eatonphil** [comment]
It'd just be a boolean variable on the file panel info in runner/state.go. But yup just push whatever and I'll help out then!
