### ISSUE TITLE
Does this work on apple silicon natively?

### ISSUE THREAD

**Issue by anarchy89** [multiprocessio/datastation#270]
Do the pre built binaries work on apple silicon or does it use Rosetta?

**Comment by akhenakh** [comment]
Yes the official binary is working on M1 using Rosetta. 
Prefer doing a Silicon native build if you can, it will perform better. 
Hopefully the author can update the test workflow in the future.

**Comment by eatonphil** [comment]
This won't be possible until https://github.com/github/roadmap/issues/528.
