### ISSUE TITLE
SSH ignoring non-standard port

### ISSUE THREAD

**Issue by loicalleyne** [multiprocessio/datastation#274]
DataStation Desktop CE 0.11.0

For security reasons we don't use port 22, when trying to run a panel using a server defined in the SSH Connections section getting this error:

[INFO] 2022-06-23T14:10:01 Failed to eval: DSError {
  "name": "Error",
  "message": "Could not connect to remote server: dial tcp _[IP REDACTED]_:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

**Comment by eatonphil** [comment]
Hey thank you! Could you please share a screenshot of the server settings and whatever other panel or connector settings shown too? Black out whatever you need.

**Comment by benjaminpwarren** [comment]
Not OP, but same issue - seems like the port value is ignored and the default of 22 is used instead. Screenshot attached

![datastation_ssh_error](https://user-images.githubusercontent.com/5371827/177432038-c262ffa3-3e02-4519-8930-a4c3979d281d.png)
.

**Comment by eatonphil** [comment]
In retrospect I don't know why I included the Port field. If you include port in the address then it should work.

I'm just going to drop the Port input in the next release and indicate you should specify the port if not :22 the address field like `1.1.1.1:2929`.

**Comment by eatonphil** [comment]
Here's what this will look like in the future:

![image](https://user-images.githubusercontent.com/3925912/177650450-8c10cb85-3f5f-484e-b589-686c502797b4.png)
