### ISSUE TITLE
Optional auth?

### ISSUE THREAD

**Issue by dannysummerlin** [multiprocessio/datastation#284]
https://github.com/multiprocessio/datastation/blob/4a4e87ff9ab180731b85e2476c4ab0db0c71f551/server/auth.ts#L51

locally I had to change this from log.error to log.info in order to skip using OpenID, otherwise it just hard errors out. I don't know if that is intentional, or if there is some other way to skip OpenID, just wanted to note it here

**Comment by eatonphil** [comment]
It works for me. Share the whole logs? It's likely erroring out on something else.

**Comment by dannysummerlin** [comment]
Sorry, been running running, I'll try to get those captured sooner than later; I'd like to contribute to getting the server component running in Windows anyways so I'll need to do better and pay attention soon anyways, I'll just close this ticket for now!

**Comment by eatonphil** [comment]
Ah, running the server on Windows is not a goal at the moment. It only works on Linux.
