### ISSUE TITLE
Where the created projects saved

### ISSUE THREAD

**Issue by jubinmytheen** [multiprocessio/datastation#299]
We have deployed DataStation Server CE on our ubuntu server without passing database details in Config.yaml file. The UI is working fine. And we can create new project without any issues. To take backup of the created projects, could you please share how the created projects saved on the DataStation?

**Comment by eatonphil** [comment]
Hey! That's awesome to hear! All the project files should be in /home/datastation/DataStationProjects/*.dsproj.
