### ISSUE TITLE
Link to Online Environment is broken

### ISSUE THREAD

**Issue by sebastianvitterso** [multiprocessio/datastation#50]
In the feature list of the datastation.multiprocess.io, the link to app.datastation.multiprocess.io os broken.

The `href` of the `<a>`-tag starts with `https//app...` (note the missing colon), and should be replaced with `https://app...`

![image](https://user-images.githubusercontent.com/37065184/134624071-ae55dabf-e1d8-4a6e-bef6-8d5b48ad6db0.png)

![image](https://user-images.githubusercontent.com/37065184/134624329-c630dafd-2033-4f05-a32d-89a2e923c512.png)

**Comment by eatonphil** [comment]
Thank you! I just pushed the fix.

![image](https://user-images.githubusercontent.com/3925912/134671443-34123e18-7a5c-48b0-ac58-44f62b6d8ef8.png)
