### ISSUE TITLE
Feature Request: Add support for Prometheus and PromQL

### ISSUE THREAD

**Issue by ryuheechul** [multiprocessio/datastation#51]
I am just introduced to https://datastation.multiprocess.io/.
This seems to be a really cool approach and I like that it supports mix and match between data sources and scripting languages.
I just thought it would be pretty cool if this project supports Prometheus and PromQL, https://prometheus.io/docs/prometheus/latest/querying/basics/ down the road.

**Comment by eatonphil** [comment]
Hey! Thanks for the suggestion. Yes that's definitely something I'm thinking about! Both time series databases and document databases should be coming soon.

**Comment by eatonphil** [comment]
Prometheus support has been merged! It will be available in the next release, probably early next week.
