### ISSUE TITLE
Use panel.id (uuid) for panelSource instead of panel index

### ISSUE THREAD

**Issue by eatonphil** [multiprocessio/datastation#57]
Everywhere that a panel references another one in configuration (table, graph, and visual transform panels) they use the index of the panel. This is fragile and I can't remember any reason for it to be like this. Instead these panels should reference `panel.id`, a uuid, instead of the panel index. This way when panels are reordered or added/removed the reference stays constant.

**Comment by Akshansh99** [comment]
@eatonphil I would like to work on it. Could you assign it to me?

**Comment by eatonphil** [comment]
No need, just give it a shot! Read the HACKING.md and ARCHITECTURE.md pages if you need and join the Discord channel if you get stuck.

**Comment by Akshansh99** [comment]
@eatonphil Could you please reference me an occurrence of this happeing? It would be very helpful for me. Thanks :)

**Comment by eatonphil** [comment]
This isn't a bug, it's developing a small feature. Table panels, graph panels, and visual transform panels all have a concept of [panel source]()https://github.com/multiprocessio/datastation/blob/master/shared/state.ts#L306_. This shows up in the UI [here](https://github.com/multiprocessio/datastation/blob/master/ui/panels/TablePanel.tsx#L87), [here](https://github.com/multiprocessio/datastation/blob/master/ui/panels/GraphPanel.tsx#L236) and [here](https://github.com/multiprocessio/datastation/blob/master/ui/panels/FilterAggregatePanel.tsx#L124).

The [PanelSourcePicker component](https://github.com/multiprocessio/datastation/blob/master/ui/components/PanelSourcePicker.tsx#L20) itself is what sets the value of panelSource to be the integer index of the panel rather than the panel's `id` field that is a uuid.

If you take this on you would start by swapping the PanelSourcePicker code out from using index to using the panel's id field, fix all the TypeScript errors that happen because this would now be a string not a number.

Then you'd fix the evaluation implementation [here](https://github.com/multiprocessio/datastation/blob/master/desktop/panel/columns.ts#L24) and [here](https://github.com/multiprocessio/datastation/blob/master/desktop/panel/filagg.ts#L51) to be using the uuid rather than the index offset.

But Github issues aren't a good place to have extended discussion about setup so if you're interested then let's talk on Discord if you get stuck more.
